[FEATURE] Προσθήκη λειτουργίας new_station
CerebruxCode/shelldio pull request #107
Opened 2020-11-26 16:21 UTC by tasakos-dev

Προσθήκη λειτουργίας new_station η οποία προσθέτει έναν νέο σταθμό στο all_station.txt

2020-12-05 15:40 UTC, cerebrux requested changes
δες το comment εδώ https://github.com/CerebruxCode/shelldio/issues/106#issuecomment-739308123

2020-12-05 18:23 UTC, zoispag approved these changes
LGTM! Δες 2 minor comments για consistency.

2020-12-05 18:23 UTC, zoispag commented on shelldio.sh
> +new_station(){
```suggestion
new_station() {
```

2020-12-05 18:23 UTC, zoispag commented on shelldio.sh
> +	done
```suggestion
	done

```

2020-12-05 18:25 UTC, zoispag requested changes
Sorry, μόλις παρατήρησα 2 ακόμα πραγματάκια.

2020-12-05 18:25 UTC, zoispag commented on shelldio.sh
> +			ραδιοφωνικούς σταθμούς (στο αρχείο $all_stations)
Κι εδώ θέλει μια αλλαγή!

2020-12-05 18:25 UTC, zoispag commented on shelldio.sh
> +	list_stations "$all_stations"
Μήπως πρέπει να κάνουμε print τους αγαπημένους σταθμούς εδώ;

2020-12-05 18:32 UTC, tasakos-dev commented on shelldio.sh
> +			ραδιοφωνικούς σταθμούς (στο αρχείο $all_stations)
Έγινε!

2020-12-05 19:01 UTC, tasakos-dev commented on shelldio.sh
> +	list_stations "$all_stations"
Τελικά να κάνω και αυτήν την αλλαγή;

2020-12-07 21:19 UTC, zoispag commented on shelldio.sh
> +new_station() {
```suggestion
new_station () {
```

For consistency

2020-12-07 21:19 UTC, zoispag commented on shelldio.sh
> +
```suggestion
```

2020-12-07 22:43 UTC, zoispag approved these changes

2020-12-27 08:45 UTC, merged